imports:
    - { resource: framework.yml }
    - { resource: doctrine.yml }
    - { resource: jwt.yml }
    - { resource: fosrest.yml }
    - { resource: twig.yml }
    - { resource: swiftmailer.yml }
    - { resource: upload.yml }
