app.swagger_ui:
  path: /api-doc/{area}
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api-doc/{area}.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }